### ISSUE TITLE
[CLI] Add `mv` command to volumes 

### ISSUE THREAD

**Issue by mernit** [beam-cloud/beta9#219]
## Is your feature request related to a problem?

No.

## Describe the solution you'd like

It would be nice to move files around volumes using a `mv` CLI command. For example:

```
beta9 volume mv ./file.txt ./artifacts/text-files/file.txt
```

```
beta9 volume mv [SOURCE-PATH] [DESTINATION-PATH]
```

**Comment by jsun-m** [comment]
#265
