### ISSUE TITLE
Can it work with a custom http server?

### ISSUE THREAD

**Issue by JoanFM** [beam-cloud/beta9#431]
I have seen in the documentation you deploy functions, can one deploy a custom http server? like a fastapi app?

thanks

**Comment by mernit** [comment]
Hey @JoanFM 👋

We're working on this now -- it should be released at the end of this week. For context, the functionality would look like this:

```
from beam import asgi 


@asgi(gpu="A100-40")
def run_web_server():

    from fastapi import FastAPI, JSONResponse
    app = FastAPI()

    @app.post("/inference")
    async run_inference():
      # Do some inference
      return JSONResponse({...})

return app
```

**Comment by mernit** [comment]
@JoanFM we have a PR open for this [here](https://github.com/beam-cloud/beta9/pull/434)

**Comment by JoanFM** [comment]
thanks a lot

**Comment by mernit** [comment]
@JoanFM this is now in prod
