### ISSUE TITLE
Suggestion: Improve release details with automated changelog generation

### ISSUE THREAD

**Issue by aaydin-tr** [beam-cloud/beta9#463]
Hey there,

First off, thanks for all the hard work on this project—it's really awesome!

I had a small suggestion that I think could be really helpful for people like me who like to keep track of what’s happening with the code. It would be great if the releases included more detailed changelogs, especially focusing on the key pull requests and commits. This would make it a lot easier to see what’s new and what’s been improved.

For instance, something like [GoReleaser](https://goreleaser.com/) can automate this and pull in details from commit messages or PR titles. But of course, there are other tools that can do this too.

What do you think? Just a thought—happy to hear your take on it!

Thanks for considering it! 😊

**Comment by jsun-m** [comment]
@aaydin-tr Thanks for you suggestion! We are aware of this problem. There a lot of releases that have individual changes and like you said, it's difficult to see what's going on. I'll chat with the team and see what we can do about this.

**Comment by mernit** [comment]
Hey @aaydin-tr - we added automated changelogs to this page: https://docs.beam.cloud/v2/releases/10-18-24
