### ISSUE TITLE
Does the solution support privatized deployment? Is there a commercial solution?

### ISSUE THREAD

**Issue by ToviHe** [beam-cloud/beta9#484]
Hello, our company has underlying infrastructure requirements for serverless GPU, mainly to support the scheduling of large model inference services within our company. Due to some limitations of the company, we cannot use public cloud services and can only adopt private cloud deployment solutions. I discovered beam on reddit, and also found out that there is an open source version, which is incredible. I would like to ask if this open source version has corresponding commercial support?

**Comment by mernit** [comment]
Hi @ToviHe, thanks for reaching out! Yes Beam/Beta9 can be deployed on private clouds. We offer commercial support as part of our enterprise plan, if you're interested let's [setup a call to discuss](calendly.com/elimernit/30min).

**Comment by ToviHe** [comment]
> Hi @ToviHe, thanks for reaching out! Yes Beam/Beta9 can be deployed on private clouds. We offer commercial support as part of our enterprise plan, if you're interested let's [setup a call to discuss](calendly.com/elimernit/30min).

Thanks for your answer. I would like to ask whether the commercialization plan corresponding to this open source technology is supported by Chinese domestic companies? Due to some policy issues, our company only accepts domestic enterprises in China for commercialization.

**Comment by mernit** [comment]
> > Hi @ToviHe, thanks for reaching out! Yes Beam/Beta9 can be deployed on private clouds. We offer commercial support as part of our enterprise plan, if you're interested let's [setup a call to discuss](calendly.com/elimernit/30min).
> 
> Thanks for your answer. I would like to ask whether the commercialization plan corresponding to this open source technology is supported by Chinese domestic companies? Due to some policy issues, our company only accepts domestic enterprises in China for commercialization.

I am not sure I fully understand the question, but the vendor (beam.cloud) is an American company

**Comment by ToviHe** [comment]
> > > Hi @ToviHe, thanks for reaching out! Yes Beam/Beta9 can be deployed on private clouds. We offer commercial support as part of our enterprise plan, if you're interested let's [setup a call to discuss](calendly.com/elimernit/30min).
> > 
> > 
> > Thanks for your answer. I would like to ask whether the commercialization plan corresponding to this open source technology is supported by Chinese domestic companies? Due to some policy issues, our company only accepts domestic enterprises in China for commercialization.
> 
> I am not sure I fully understand the question, but the vendor (beam.cloud) is an American company

Thank you for your answer. We will take a look at the situation internally and look forward to cooperating with you.
