### ISSUE TITLE
If the container hosting the large model does not have Keep Warm set, will the container be destroyed if no requests come in?

### ISSUE THREAD

**Issue by ToviHe** [beam-cloud/beta9#498]
Hello, I would like to ask how long will the model instance exist by default after starting the large model container? Will GPU resources be occupied when there are no requests?

**Comment by jsun-m** [comment]
It depends on which abstraction you are using. The SDK decorator should have the default set.
For example `task_queue` has a default keep_warm_seconds of 10 but `endpoint` has a default of 180 (3 minutes)
